### ISSUE TITLE
Can't use brew install anymore

### ISSUE THREAD

**Issue by dani-newman** [allcloud-io/clisso#111]
![image](https://user-images.githubusercontent.com/78728950/110304323-1c6c0d80-8004-11eb-85e8-e76e0de1cc4b.png)

**Comment by allcloud-jonathan** [comment]
File upload didn't succeed. Fixed the upload. Should be working again.

**Comment by samrees** [comment]
We have a asdf plugin for it. https://github.com/spothero/asdf-clisso
