### ISSUE TITLE
Clisso newer than 0.7 causes 500 errors in OneLogin

### ISSUE THREAD

**Issue by samrees** [allcloud-io/clisso#113]
This is with 2FA turned on. Think it can be pretty easily reproduced. The --debug flag would be useful as while a 500 error is their problem, they won't support it without:

> Just generate data showing all the input parameters and the full HTTP header data that is returned when you get that 500 internal server error response from OneLogin.

**Comment by samrees** [comment]
```
[~]> asdf shell clisso 0.7.0
[~]> clisso get production
Authentication pending on OL Protect
Credentials written successfully to '/Users/sam.rees/.aws/credentials'
[~]> asdf shell clisso 0.8.3
[~]> clisso get production
Could not get temporary credentials: generating SAML assertion: doing HTTP request: 500 Internal Server Error
```

**Comment by allcloud-jonathan** [comment]
We switched the OneLogin API endpoint between the versions 0.7 and 0.8.

Unfortunately, we currently don't have a debug flag/statement. I missed it myself every now and then but never came around implementing it. What I commonly do is to run it from source and add a temporary debug statement in the area of the broken code. For your specific problem this would be here: https://github.com/allcloud-io/clisso/blob/master/onelogin/client.go#L177 

I'll try to look into a debug logging option soon.

**Comment by allcloud-jonathan** [comment]
BTW: I can't reproduce it on my end. For me Onelogin with a US shard works fine on 0.8.3

**Comment by samrees** [comment]
Worked with OneLogin. Apparently the problem is that we had an IP restriction listed for our Clisso client in the "Legacy API Control Panel" of OneLogin. And since Clisso does not pass the IP address to the SAML Assertion API, this uncovered a bug in OneLogin, and thus the 500 error. 

Removing the IP restriction resolved the error for us. OneLogin also promised to fix the bug. I'm going to leave the debugging info I got for this and close this issue, in the hope its googleable if someone else hits it.

Test case:
```
curl -H 'Content-Type: application/json' -H 'Authorization: bearer:<redacted>' -d '{"username_or_email":"<redacted>@<redacted>.com","password":"<redacted>","app_id":"<redacted>","subdomain":"<redacted>"}"' -X POST https://api.us.onelogin.com/api/2/saml_assertion

⠼ HTTP/1.1 500 Internal Server Error
Content-Length: 948
Cache-Control: no-cache
Content-Type: text/html; charset=utf-8
Date: Wed, 14 Apr 2021 22:29:12 GMT
P3p: CP="CAO DSP COR CURa ADMa DEVa OUR IND PHY ONL UNI COM NAV INT DEM PRE"
Status: 500 Internal Server Error
Strict-Transport-Security: max-age=63072000; includeSubDomains;
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-Request-Id: 000000-452438EF-F29B-0A0B05C5-01BB-3AC0A9-2B6F
X-Xss-Protection: 1; mode=block

    <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
           "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

    <html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">

    <head>
      <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
      <title>We're sorry, but something went wrong (500)</title>
    <style type="text/css">
    body { background-color: #fff; color: #666; text-align: center; font-family: arial, sans-serif; }
    div.dialog {
    width: 25em;
    padding: 0 4em;
    margin: 4em auto 0 auto;
    border: 1px solid #ccc;
    border-right-color: #999;
    border-bottom-color: #999;
    }
    h1 { font-size: 100%; color: #f00; line-height: 1.5em; }
    </style>
    </head>

    <body>
      <!-- This file lives in public/500.html -->
      <div class="dialog">
        <h1>We're sorry, but something went wrong.</h1>
        <p>We've been notified about this issue and we'll take a look at it shortly.</p>
      </div>
    </body>
    </html>
