### ISSUE TITLE
Support AWS Multi Account App - OneLogin

### ISSUE THREAD

**Issue by catrielgood** [allcloud-io/clisso#163]
In OneLogin there is an App for Multi Account access, which allows you to setup the same SAML IDP in multiple AWS Accounts. Once you select the App in OneLogin you are presented with the list of accounts to choose to connect to. This helps with customers who have many accounts and do not wish to create a OneLogin App per account but still want to have Programmatic Access with temporary keys. 

![Screen Shot 2022-04-11 at 18 14 27](https://user-images.githubusercontent.com/85223334/162771365-1bd99709-490b-4f24-bbb2-7748e4b65d7a.png)

Would be happy to assist in developing this feature, just need a few pointers on where to start since I am coming from a Python background.

**Comment by bitte-ein-bit** [comment]
Hey,
As shared internally already. This feature is available and working.

You have two options:
1. Configure the app like any other app. When you launch it, it will just ask you to select any of the returned roles.
2. Configure the app with the optional `--arn` parameter. When launched, it will work like a single-role OneLogin integration.

I'm closing this.
