### ISSUE TITLE
Store passwords in system keychains

### ISSUE THREAD

**Issue by jspc** [allcloud-io/clisso#50]
Storing passwords in system keychains would ensure that lost/ compromised machines don't leak onelogin passwords (or: if they do, it's not down to this tool).

A simple implementation could use `runtime.GOOS` to determine the OS and infer keychains from there (a good jumping off point would be via: https://github.com/tmc/keyring) and then default to the config file/ asking should it be unable to access any).

**Comment by jspc** [comment]
This is somewhere between a duplicate (sorry!) and an expansion of https://github.com/allcloud-io/clisso/issues/11

**Comment by johananl** [comment]
It is actually better than #11 , so leaving this one open and closing the old one. Thanks!

**Comment by allcloud-jonathan** [comment]
implemented in #69. @jspc thanks for the contribution of code and issue.
