### ISSUE TITLE
Commit vendor directory to allow deterministic builds

### ISSUE THREAD

**Issue by johananl** [allcloud-io/clisso#63]
Since we're adding Homebrew support, we might want to start committing the vendor directory to ensure deterministic builds on target machines when installing with Homebrew.

**Comment by allcloud-jonathan** [comment]
As stated in allcloud-io/homebrew-tools#1 I wouldn't rush things and look into supporting bottles asap.

**Comment by allcloud-jonathan** [comment]
Is this still needed?
