### ISSUE TITLE
Move to Go modules?

### ISSUE THREAD

**Issue by johananl** [allcloud-io/clisso#65]
Moving from `dep` to Golang [modules](https://github.com/golang/go/wiki/Modules) can make dependency management and building easier. It's nice to be able to simply `git clone && make` anywhere, without thinking about `GOPATH` etc.

**Comment by allcloud-jonathan** [comment]
Sounds like a good idea. I would start the move just yet but wait until it's not labeled experimental anymore.

**Comment by johananl** [comment]
This could take a year :-)
But IIRC we don't have to stop supporting `dep`, we can do both in parallel.
