### ISSUE TITLE
Handle missing ~/.aws directory

### ISSUE THREAD

**Issue by johananl** [allcloud-io/clisso#75]
At the moment, when trying to run `clisso get` when the `~/.aws` directory doesn't exist, Clisso exits with the following error:

```
Error processing credentials: writing credentials to file: open /Users/<user>/.aws/credentials: no such file or directory
```

It is probably safe to create this directory if it doesn't exist, and perhaps show a warning to the user. The `~/.aws/credentials` file is already created automatically if it doesn't exist.

**Comment by allcloud-jonathan** [comment]
solved in https://github.com/allcloud-io/clisso/pull/92
