### ISSUE TITLE
Question: how to assign a default AWS region?

### ISSUE THREAD

**Issue by itonics-tbeauvais** [allcloud-io/clisso#88]
Everything I use Clisso get, I have to set up the AWS region again. Can there be a way to set this up in the provider? I can't seem to use the "region" for this as it seems that it is used for something else.

**Comment by johananl** [comment]
Hi @itonics-tbeauvais.

The AWS region setting tells the AWS CLI/SDK which API endpoint to use when calling an AWS service. IAM credentials are *global* on AWS, that is - the same credentials can be used with multiple regions.
Therefore, Clisso doesn't deal with AWS regions and has no real way of influencing which region you use when calling an AWS service. It is up to you to specify the AWS region you use.

I suggest you do one of the following, depending on your use case and personal preference.

- Configure a default AWS region using the AWS CLI (run `aws configure` and set a region interactively).
- Set the `AWS_REGION` environment variable in your shell.
- Specify the `--region` flag in your AWS CLI commands, or set the relevant variable when creating an AWS client using one of the AWS SDKs.

Good luck!
