### ISSUE TITLE
Error - Could not get temporary credentials: EOF

### ISSUE THREAD

**Issue by yodaforce11138** [allcloud-io/clisso#91]
Hello,
I'm trying to setup the clisso on my windows machine. The okta is configured with the MFA (okta verify). I tried various ways to get the temp token. It accepts my password and challenges for the MFA (OTP from my MFA device - Okta verify app) and then gets the following error
"Could not get temporary credentials: EOF"

Here are the various commands that I tried
C:\Program Files\clisso-windows-386.exe>clisso.exe get okta
Please enter my-provider password:
Please enter the OTP from your MFA device: 951212
Could not get temporary credentials: EOF

C:\Program Files\clisso-windows-386.exe>clisso.exe get okta -w "C:\Users\dinesh.katariya\.aws\credentials"
Please enter my-provider password:
Please enter the OTP from your MFA device: 412350
Could not get temporary credentials: EOF

C:\Program Files\clisso-windows-386.exe>clisso.exe get okta -s
Please enter my-provider password:
Please enter the OTP from your MFA device: 009326
Could not get temporary credentials: EOF

**Comment by johananl** [comment]
Hey @yodaforce11138. Do you have MFA enabled globally on Okta or at the app itself? Please keep in mind that currently app-level MFA on Okta [isn't supported](https://github.com/allcloud-io/clisso#caveats-and-limitations).

Note to self - we should probably add support for that as well, and we should definitely improve the error there.

**Comment by allcloud-jonathan** [comment]
Closed due to inactivity

**Comment by dani-newman** [comment]
Hey, 

Same issue here. We've got globally enabled MFA for our OKTA account.
