### ISSUE TITLE
Could not get temporary credentials: generating SAML assertion: doing HTTP request: 404 Not Found

### ISSUE THREAD

**Issue by Einavf77** [allcloud-io/clisso#94]
one of my users keep getting this error when after entering the password.
we are using the latest clisso version with onelogin and aws.

on my Mac i'm able to use the clisso without problems.

thanks,

**Comment by allcloud-jonathan** [comment]
Have you verified the config is the same/similar? Check `~/.clisso.yaml` 
Are both systems a Mac?

**Comment by Einavf77** [comment]
HI Jonathan ,
my problem was a lack of permissions in the roles in the onelogin app.
thanks,
