### ISSUE TITLE
No way to specify pretty names for IAM roles

### ISSUE THREAD

**Issue by martinhanzik** [allcloud-io/clisso#95]
There does not seem to be a way to do something like https://github.com/onelogin/onelogin-python-aws-assume-role/blob/master/accounts.yaml.template
It would be nice, if you could give names to the ARNs you choose from, so you don't have to go by the account ID.

**Comment by esilva-everbridge** [comment]
I can look at adding this. I added it to the onelogin python script which I'd like to replace with this tool.

**Comment by allcloud-jonathan** [comment]
#96 will implement this.
